### ISSUE TITLE
Unresolved imports in EvaluationFramework

### ISSUE THREAD

**Issue by dstrueber** [sinemgetir/state-elimination-mt#1]
Hi,

the following imports in classes of the EvaluationFramework project cannot be resolved:

import automata.State;
import automata.fsa.FSATransition;
import automata.fsa.FiniteStateAutomaton;

I could not find the imported classes in the a text-search on the repository as well. Is there something missing?

**Comment by sinemgetir** [comment]
Hi,
thank you for the question.
it is a part of code from the external tool JFLAP (we could not upload it directly on Github since it is not our implementation even it is open source. ). therefore, we say it in README you can either download the simplified version from [here](https://www.informatik.hu-berlin.de/de/forschung/gebiete/se/research/ongoingprojects/ensure/ttc):
or from [JFLAP](http://www.jflap.org/) website which includes much more than you need.
i would be happy to answer if you have any further questions.

**Comment by dstrueber** [comment]
Thanks! From the paper and README, I understood that you have a JFLAP-based reference solution and where to obtain it. I just didn't notice the reference solution is required to get the evaluation framework to run.

To be on the safe side: To evaluate my own solution, the idea is that I remove the JFLAP imports, and replace them with imports of my own stuff. Correct?

**Comment by sinemgetir** [comment]
Yes unfortunately our implementation is dependent on Jflap classes :( Sure
you can replace them with your own imports. Thanks.

16 May 2017 11:44 tarihinde "Daniel Strüber" <notifications@github.com>
yazdı:

Thanks! From the paper and README, I understood that you have a JFLAP-based
reference solution and where to obtain it. I just did't notice the
reference solution is required to get the evaluation framework to run.

To be on the safe side: To evaluate my own solution, the idea is that I
remove the JFLAP imports, and replace them with imports of my own stuff.
Correct?

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/sinemgetir/state-elimination-mt/issues/1#issuecomment-301730874>,
or mute the thread

**Comment by dstrueber** [comment]
OK, thanks for clarifying. Best regards!
